spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: Amit@9997

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: sanjeev
      password: 12345

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.payment_service.dto.OrderCreatedEvent
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    listener:
      observation-enabled: true

    template:
      observation-enabled: true

server:
  port: 8086

management:
  otlp:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
